# main.yml
name: deploy to tencentyun
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:14
      - name: use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            ARGS: '-rltgoDzvO --delete'
            SOURCE: dist/*
            REMOTE_HOST: ${{ secrets.HOST }}
            REMOTE_USER: root
            TARGET: /www/wwwroot/www.merlin218.top/uml-exercise
