# main.yml
name: deploy to tencentyun
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:14
      - name: use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      # Deploy
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
            # 本地.ssh文件下的私钥id_rsa，存在secrets的TOKEN中
            SSH_PRIVATE_KEY: ${{ secrets.TOKEN }} 
            # 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的文件
            ARGS: "-avzr --delete" 
            # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
            SOURCE: "dist/" 
            # 服务器域名
            REMOTE_HOST: ${{ secrets.HOST }}
            # 腾讯云默认用户名为root
            REMOTE_USER: ${{ secrets.USERNAME }} 
            # 目标目录
            TARGET: "/www/wwwroot/uml-exercise"
