# main.yml
name: deploy to tencentyun
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:14
      - name: use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      # Deploy
      - name: Deploy to Server  # 第四步，rsync推送文件
        uses: AEnterprise/rsync-deploy@v1.0  # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.TOKEN }}   # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc'   # rsync参数，排除.pyc文件
          SERVER_PORT: '22'  # SSH端口
          FOLDER: ./dist/*  # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.HOST }}  # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.USERNAME }}  # 引用配置，服务器登录名
          SERVER_DESTINATION: ${{ secrets.TARGET }}   # 部署到目标文件夹
