# main.yml
name: deploy to tencentyun
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:14
      - name: use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      # Deploy
      - name: Deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY }}
        with:
          flags: '-avzr'
          options: ''
          ssh_options: ''
          src: 'dist/'
          dest: 'root@119.91.229.224:/www/wwwroot/uml-exercise'
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
